### ISSUE TITLE
Double tapping the menu button error

### ISSUE THREAD

**Issue by ddaddy** [lminhtm/LMDropdownView#4]
If you accidentally double tap the menu button (Or just press a second time before the menu fully visible) then the table view seems to go out of position.

The same thing happens briefly if you press the Menu button to close the menu. The table shifts upwards slightly before it moves.

I've tried to figure out what could be causing it but to no avail.
If I set kDefaultBounceHeight to 0, it no longer happens, however when it bounces it is black instead of coloured behind.

**Comment by lminhtm** [comment]
This error is fixed ^^
