### ISSUE TITLE
DropDownView hidden behind navigation bar?

### ISSUE THREAD

**Issue by OmarBizreh** [lminhtm/LMDropdownView#9]
I'm using LMDropdownView in a swift project this is my code:
```Swift
table.frame = CGRectMake(0, 0, CGRectGetWidth(self.view.bounds), CGRectGetHeight(self.view.bounds) / 2);
        table.dataSource = self
        table.delegate = self
        table.separatorStyle = .None
        table.registerNib(UINib(nibName: "ChildTableViewCell", bundle: NSBundle.mainBundle()), forCellReuseIdentifier: "cell")
        table.backgroundColor = UIColor(red:40.0/255,green:196.0/255,blue:80.0/255,alpha:1)
        
        
        if drop.isOpen {
            drop.hide()
        }else{
           drop.showFromNavigationController(self.navigationController!, withContentView: table)
       }
```
and this is the result: 

![untitled](https://cloud.githubusercontent.com/assets/3820516/11344915/a89bfa44-921c-11e5-92d1-966ce68b4cb1.png)

LMDropdownview seems to always start from point x = 0, y = 0. What should I do? I checked your demo code and couldn't reach a solution.

Thanks in advance.

**Comment by lminhtm** [comment]
@OmarBizreh you should try this method:
- (void)showInView:(UIView *)containerView withContentView:(UIView *)contentView atOrigin:(CGPoint)origin;

Hope it work for you.

**Comment by OmarBizreh** [comment]
Thanks I used your approach and it worked.
code is:
```Swift
drop.showInView(self.view!, withContentView: table, atOrigin: CGPoint(x: 0, y: self.navigationController!.navigationBar.frame.size.height + UIApplication.sharedApplication().statusBarFrame.size.height))
```

It seems something is wrong in my View so that your control is starting from point x = 0, y = 0

**Comment by RajChanchal** [comment]
I am using the showInView Method, but the contentView's subviews are distorted i.e. they don't follow autolayout.

**Comment by famictech2000** [comment]
Can someone provide a sample project!?

**Comment by RajChanchal** [comment]
@famictech2000 This repo has a demo project already. Check that.
